### ISSUE TITLE
Unexpected versioning behavior when using release-it

### ISSUE THREAD

**Issue by ArcasGabriel** [release-it-plugins/workspaces#97]
## Description
Having a monorepo setup, when using the release-it tool with the --major flag, the major version number is correctly incremented from its current value to 1.0.0. However, when using the --patch flag after that, the patch version number is unexpectedly downgraded to 0.0.1 instead of continuing from 1.0.0 to 1.0.1.
This behavior is unexpected because it deviates from the Semantic Versioning standard that the project follows.
```
"release-it-patch": "release-it patch -n --verbose --ci --github.autoGenerate",
"release-it-minor": "release-it minor -n --verbose --ci --github.autoGenerate",
"release-it-major": "release-it major -n --verbose --ci --github.autoGenerate"
```

## Steps to reproduce
1. Install release-it workspace plugin and configure it for the project that follows Semantic Versioning.
2. Create a GitHub Action that reads input (minor/major/patch).
3. Run an workflow with the command release-it --major. The major version number should be incremented to 1.0.0.
4. Run an workflow with the command release-it --patch. The patch version number should be incremented to 1.0.1, but it is unexpectedly downgraded from 1.0.0 to 0.0.1.

**Expected behavior**: When using release-it with the --patch flag, the patch version number should continue from the current version to the next patch version, in accordance with the Semantic Versioning standard.

**Actual behavior**: When using release-it with the --patch flag, the patch version number is incremented to the next patch version, but it does not continue from the current version as expected.

## Additional information:

The project follows the Semantic Versioning standard.
This behavior is unexpected and could cause confusion for users and contributors.

![image](https://user-images.githubusercontent.com/38486343/221375597-e0f571eb-bf50-4353-82fa-1388f738385d.png)

My config:
```
{
  "hooks": {
    "after:release": "echo Successfully released ${name} v${version} to ${repo.repository}."
  },
  "plugins": {
    "@release-it-plugins/workspaces": {
      "additionalManifests": {
        "dependencyUpdates": ["functions/*/package.json"]
      },
      "workspaces": ["parsers/*", "fetchers/*", "senders/*"],
      "skipChecks": true
    }
  },
  "github": {
    "release": true,
    "tokenRef": "GITHUB_TOKEN"
  },
  "npm": false
}
```

Github Action

```
on:
  workflow_dispatch:
    inputs:
      releaseLevel:
        description: 'Release Level'
        required: true
        default: 'patch'
        type: 'choice'
        options:
          - patch
          - minor
          - major

     - name: Build
        run: |
          npm run build
      - name: Release with release-it
        if: steps.login.outcome == 'success'
        run: |
          echo "$RELEASE_LEVEL"
          npm run release-it-$RELEASE_LEVEL
```
